### ISSUE TITLE
Bucket tpch does not exist

### ISSUE THREAD

**Issue by kikesensei** [josephmachado/analytical_dp_with_sql#14]
**Describe the bug**
Upon trying the example in page 34 of the book the following query:
```slq
CREATE SCHEMA minio.tpch WITH (location = 's3a://tpch/');
```
fails with the following error message:
```
[2024-08-06 09:52:46] [16777216] Query failed (#20240806_075244_01597_eke7s): Got exception: java.io.FileNotFoundException Bucket tpch does not exist
[2024-08-06 09:52:46] io.trino.hive.thrift.metastore.MetaException: Got exception: java.io.FileNotFoundException Bucket tpch does not exist
```

**To Reproduce**
1. Open Trino console.
2. Run `DROP SCHEMA IF EXISTS minio.tpch;`
3. `CREATE SCHEMA minio.tpch WITH (location = 's3a://tpch/');`
4. See error.

**Expected behavior**
Successful creation of new schema.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by josephmachado** [comment]
Hey @kikesensei TY for reporting the issue.
Do you mind opening your browser and checking localhost:9000 (username: minio and password: minio123) to see if the folders `tpch` and `icebergwarehouse` exists?

Are you by any chance using mac m1 (or higher) I think there may be an issue with the [container](https://github.com/josephmachado/analytical_dp_with_sql/blob/7c57bb75141df2cc9d1439ad57038c3aa0781478/docker-compose.yml#L57) I used to create those folders.

If you are using m1 (or higher) do you mind manually creating the `tpch` and `icebergwarehouse` folder via localhost:9000.

I will put up a fix for this ASAP!

**Comment by kikesensei** [comment]
Hi @josephmachado thanks for the quick reply.
Yes my laptop has the Apple M1 pro chip.
I got an error on my machine that port 9000 was already in used, so I changed my `docker-compose.yml` to 
```yaml
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    hostname: minio
    container_name: minio
    platform: linux/amd64
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - trino-network
```

And when I go to localhost:9002 I get re-directed to localhost:9001, where I cannot see any folders
